# Generated by Django 2.0.4 on 2018-11-03 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email')),
                ('original_name', models.CharField(blank=True, max_length=100, verbose_name='Имя пользователя')),
                ('surname', models.CharField(blank=True, max_length=100, verbose_name='Имя пользователя')),
                ('bill', models.FloatField(default=0.0, verbose_name='Счет')),
                ('activated', models.BooleanField(default=False, verbose_name='Активен')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOneCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.SiteUsers')),
            ],
        ),
    ]
