# Generated by Django 2.0.4 on 2018-11-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useronecodes',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Использован'),
        ),
        migrations.AlterField(
            model_name='siteusers',
            name='login',
            field=models.CharField(max_length=100, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='useronecodes',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Одноразовый код'),
        ),
    ]
